### ISSUE TITLE
Repo Changes before next Hacktoberfest

### ISSUE THREAD

**Issue by beardicus** [do-community/cloud_haiku#355]
I wanted to write down some notes about things we can do differently to streamline this repo before the next Hacktoberfest.

## Documentation
- [x] Update [the PR tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) to not use `git add -a` by default, so fewer people check in errant files like `package-lock.json`
- [x] Give more details in the README about the test suite, and ask folks to not disable testing before submitting their PR

## Automation
- [ ] Add action to close PR w/ a message if user is not a first-time contributor
- [ ] Add action to flag as invalid and close after 6 days of no response to change requests

## Testing
- [ ] Test that haiku files are in the `_haikus` directory and end in `.md` file extension
- [ ] Test for `  ` or `<br>` line endings
- [ ] Smarter failure messages for malformed YAML frontmatter
- [ ] Fail if more than one file is changed in a PR
- [ ] Add `ci-reporter` integration (or GH Actions equivalent) to push test failure information into PR comments
- [ ] Switch from Travis to GH Actions

**Comment by ltagliaferri** [comment]
This sounds good to me. I think going forward we can just indicate that contributors to use `<br>` tags to make it more straightforward for folks rather than giving them options. What do you think?

**Comment by ltagliaferri** [comment]
Do you think I should update the README so that folks should just use the `<br>` tag at the end of line breaks? That may make the testing easier and Lyn's Hacktoberfest video uses the tags.

**Comment by beardicus** [comment]
Yeah, I think that'd be good.

**Comment by ltagliaferri** [comment]
Also... Code of Conduct 😄

**Comment by jsoref** [comment]
You're running out of time before "next Hacktoberfest" 😉  unless you mean 2021 at this point. (Might I suggest you update the issue summary to specify a specific year?)

#430 covers updating `.gitignore` to specifically save from naive `package-lock.json` adds.

https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github
Has:
> If you are looking to recursively add all changes including those in subdirectories, you can type the command `git add -A` or alternatively `git add -all` _sic_ _s.b. `--all`_ for all new files to be staged.

Someone should talk about `git config user.name` and `git config user.email`. A number of the commit authors have managed to create amusing values (I'm by far the worst offender, but I'm trying to do that, they presumably aren't.)

For 2021, please replace `master` with `main` or similar.

In https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github#create-a-new-branch it'd be nice if instead of `new-branch` the branch name was `some-feature` or similar. Yes, people are creating branches, but that's already explained, it's better to hint at good naming by including `feature` or similar in the example.

WRT CoC, please make sure to fill in all the fields. On my todo list is to file bugs against dozens (hundreds? I can't recall) of repositories whose CoC includes a contact of ~fill in your contact address here~ to report violations... 🤦 .

**Comment by jsoref** [comment]
073b2ad1443a9205c95130f06ee49702564c640a added `<br>`s to the sample (it'd be nice if this was in the description w/ a checkbox so someone could mark it as done...)

**Comment by jsoref** [comment]
btw, https://github.com/do-community/cloud_haiku/labels?q=hacktoberfest-accepted:
> Accept for hacktoberfest, will merge later

That should read:
> Accepted for hacktoberfest, will merge later

(And yes, I'm aware you have a video of adding this thing, it's still ok to improve your content and set better examples for others going forward.)
